import type { Meeting } from '../types/meeting';

/**
 * Formats a Meeting entity into a clean, comprehensive Markdown report.
 */
export function generateMeetingMarkdown(meeting: Meeting): string {
  const formattedDate = meeting.createdAt
    ? new Date(meeting.createdAt).toLocaleString(undefined, {
        dateStyle: 'medium',
        timeStyle: 'short',
      })
    : 'N/A';

  const durationStr = meeting.duration != null && meeting.duration > 0
    ? `${Math.floor(meeting.duration / 60)}m ${meeting.duration % 60}s`
    : 'Not specified';

  let md = `# ${meeting.title || 'Meeting Summary'}\n\n`;

  // Metadata block
  md += `**Date:** ${formattedDate}  \n`;
  md += `**File:** ${meeting.originalFileName || 'N/A'}  \n`;
  md += `**Duration:** ${durationStr}  \n`;
  md += `**Status:** ${meeting.status || 'COMPLETED'}  \n\n`;
  md += `---\n\n`;

  // Executive Summary
  md += `## Executive Summary\n\n`;
  if (meeting.summary && meeting.summary.trim().length > 0) {
    md += `${meeting.summary.trim()}\n\n`;
  } else {
    md += `_No executive summary generated._\n\n`;
  }

  // Key Decisions
  md += `## Key Decisions\n\n`;
  if (meeting.keyDecisions && meeting.keyDecisions.length > 0) {
    meeting.keyDecisions.forEach((decision) => {
      md += `- ${decision}\n`;
    });
    md += `\n`;
  } else {
    md += `_No key decisions recorded._\n\n`;
  }

  // Action Items
  md += `## Action Items\n\n`;
  if (meeting.actionItems && meeting.actionItems.length > 0) {
    md += `| Task | Owner | Deadline |\n`;
    md += `| :--- | :---- | :------- |\n`;
    meeting.actionItems.forEach((item) => {
      const task = (item.task || '').replace(/\|/g, '\\|');
      const owner = (item.owner || 'Unassigned').replace(/\|/g, '\\|');
      const deadline = (item.deadline || 'No deadline').replace(/\|/g, '\\|');
      md += `| ${task} | ${owner} | ${deadline} |\n`;
    });
    md += `\n`;
  } else {
    md += `_No action items recorded._\n\n`;
  }

  // Full Transcript
  md += `## Verbatim Transcript\n\n`;
  if (meeting.transcript && meeting.transcript.trim().length > 0) {
    md += `${meeting.transcript.trim()}\n\n`;
  } else {
    md += `_No transcript available._\n\n`;
  }

  md += `---\n*Generated by AI Meeting Summarizer*\n`;

  return md;
}

/**
 * Downloads meeting summary and transcript as a clean Markdown (.md) file.
 */
export function exportMeetingToMarkdown(meeting: Meeting): void {
  const markdown = generateMeetingMarkdown(meeting);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  
  const sanitizedTitle = (meeting.title || 'meeting-summary')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${sanitizedTitle || 'meeting-summary'}.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Initiates print / PDF generation using the browser's native print engine,
 * styled specifically by @media print.
 */
export function exportMeetingToPdf(): void {
  window.print();
}
